apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordsmith-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/rewrite-target: /dashboard
    nginx.ingress.kubernetes.io/app-root: /app1
spec:
  tls:
  - hosts:
    - myingress.northeurope.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: myingress.northeurope.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: kube-ops-view
          servicePort: 80
        path: /
      #- backend:
      #   serviceName: ingress-demo
      #    servicePort: 80
      #  path: /hello-world-two(/|$)(.*)