apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: php-hello-3
spec:
  replicas: 5
  minReadySeconds: 20
  selector:
    matchLabels:
      role: web
    matchExpressions:
      - {key: version, operator: In, values: [v1, v2, v3]}
  template:
    metadata:
      name: php-hello-3
      labels:
        app: php-hello
        role: web
        version: v3
    spec:
      containers:
        - name: php-hello
          image: djkormo/php-hello:v3
          env:
          - name: VERSION
            value: "3.0"
          ports:
            - containerPort: 80
              protocol: TCP