apiVersion: batch/v1
kind: Job
metadata:
  name: loadtest
  labels:
    app: loadtest
spec:
  template:
    spec:
      containers:
      - name: siege
        image: schoolofdevops/loadtest:v1
        command: ["siege",  "--concurrent=5", "--benchmark", "--time=5m", "http://vote"]
      restartPolicy: Never
  backoffLimit: 4