apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordsmith-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - myingress.northeurope.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: myingress.northeurope.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 8081
        path: /wordsmith(/|$)(.*)
      #- backend:
      #   serviceName: ingress-demo
      #    servicePort: 80
      #  path: /hello-world-two(/|$)(.*)